#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: node:20.11.1

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          script:
            - npm install -g prettier tslint
            - npm install
            - npm run build
            - tslint --project tsconfig.json -t checkstyle
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Build Image
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}:latest
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"