name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: ['20.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install required packages
        run: npm install -g prettier
      - name: Retrieve packages in package.json
        run: npm install
      - name: Build project
        run: npm run build